DROP TABLE FOLLOW;

CREATE TABLE FOLLOW(
	FOLLOWING_COUNT NUMBER PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	FOLLOWER_COUNT NUMBER NOT NULL
);

INSERT INTO FOLLOW
VALUES(0, 1, 0);

SELECT * FROM FOLLOW;